/**
 * Generates a professional Markdown export for a single finding, suitable
 * for sharing with developers, AppSec leadership, or customers.
 *
 * Safety: secrets are never included. Evidence descriptions use the same
 * redacted form the UI displays.
 */
import type { Finding } from "@/lib/types";

export function exportFindingMarkdown(finding: Finding): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${finding.title}`);
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("|---|---|");
  lines.push(`| **Severity** | ${cap(finding.severity)} |`);
  lines.push(`| **Status** | ${cap(finding.status)} |`);
  lines.push(`| **Type** | ${finding.finding_type.toUpperCase()} |`);
  if (finding.rule_id) {
    lines.push(`| **Rule** | \`${finding.rule_id}\` |`);
  }

  // Location
  const loc = findingLocation(finding);
  if (loc) {
    lines.push(`| **Location** | \`${loc}\` |`);
  }
  lines.push("");

  // Description
  if (finding.description) {
    lines.push("## Description");
    lines.push("");
    lines.push(finding.description);
    lines.push("");
  }

  // Analysis Trace
  if (finding.taint_paths && finding.taint_paths.length > 0) {
    lines.push("## Analysis Trace");
    lines.push("");
    for (const step of finding.taint_paths) {
      const kind = step.step_kind.charAt(0).toUpperCase() + step.step_kind.slice(1);
      lines.push(
        `${step.step_index + 1}. **[${kind}]** ${step.detail} — \`${step.file_path}:${step.line_start}\``,
      );
    }
    lines.push("");
  }

  // Remediation
  const rem = finding.remediation;
  if (rem) {
    lines.push("## Why It Matters");
    lines.push("");
    lines.push(rem.why_it_matters);
    lines.push("");

    lines.push("## How to Fix");
    lines.push("");
    lines.push(rem.how_to_fix);
    lines.push("");

    lines.push("## Safe Example");
    lines.push("");
    lines.push("```java");
    lines.push(rem.safe_example);
    lines.push("```");
    lines.push("");

    if (rem.developer_notes) {
      lines.push("## Developer Notes");
      lines.push("");
      lines.push(rem.developer_notes);
      lines.push("");
    }

    if (rem.verification_checklist.length > 0) {
      lines.push("## Verification Checklist");
      lines.push("");
      for (const item of rem.verification_checklist) {
        lines.push(`- [ ] ${item}`);
      }
      lines.push("");
    }

    if (rem.references.length > 0) {
      lines.push("## References");
      lines.push("");
      for (const ref of rem.references) {
        lines.push(`- [${ref.title}](${ref.url})`);
      }
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push(
    `*Generated by SentinelCore on ${new Date().toISOString().split("T")[0]}*`,
  );

  return lines.join("\n");
}

function findingLocation(f: Finding): string | null {
  if (f.file_path) {
    return f.line_number ? `${f.file_path}:${f.line_number}` : f.file_path;
  }
  if (f.url) {
    return [f.method, f.url, f.parameter ? `(param: ${f.parameter})` : ""]
      .filter(Boolean)
      .join(" ");
  }
  return null;
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
