/**
 * Generates a professional Markdown scan report with executive summary
 * and technical appendix. Suitable for sharing with AppSec leadership,
 * developers, or customers.
 *
 * Safety: no secrets are included. Finding descriptions use the standard
 * redacted form.
 */
import type { Scan, Finding } from "@/lib/types";

export interface ScanReportData {
  scan: Scan;
  findings: Finding[];
}

export function exportScanReportMarkdown(data: ScanReportData): string {
  const { scan, findings } = data;
  const lines: string[] = [];

  // Title
  lines.push(`# SentinelCore Scan Report`);
  lines.push("");

  // Scan metadata table
  lines.push("## Scan Overview");
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("|---|---|");
  lines.push(`| **Scan ID** | \`${scan.id.slice(0, 8)}\` |`);
  lines.push(`| **Type** | ${scan.scan_type.toUpperCase()} |`);
  if (scan.scan_profile) lines.push(`| **Profile** | ${cap(scan.scan_profile)} |`);
  lines.push(`| **Status** | ${cap(scan.status)} |`);
  if (scan.project_name) lines.push(`| **Project** | ${scan.project_name} |`);
  if (scan.target_label || scan.target_base_url) {
    lines.push(`| **Target** | ${scan.target_label || scan.target_base_url} |`);
  }
  if (scan.source_artifact_name) {
    lines.push(`| **Source Artifact** | ${scan.source_artifact_name} |`);
  }
  lines.push(`| **Created** | ${formatDate(scan.created_at)} |`);
  if (scan.started_at) lines.push(`| **Started** | ${formatDate(scan.started_at)} |`);
  if (scan.finished_at) lines.push(`| **Completed** | ${formatDate(scan.finished_at)} |`);
  lines.push(`| **Findings** | ${findings.length} |`);
  lines.push("");

  // Executive summary
  const counts = severityCounts(findings);
  lines.push("## Executive Summary");
  lines.push("");
  lines.push(`This ${scan.scan_type.toUpperCase()} scan identified **${findings.length} finding${findings.length !== 1 ? "s" : ""}** across the target.`);
  lines.push("");
  lines.push("### Severity Breakdown");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|---|---|");
  for (const [sev, count] of Object.entries(counts)) {
    if (count > 0) {
      lines.push(`| ${sevEmoji(sev)} **${cap(sev)}** | ${count} |`);
    }
  }
  lines.push("");

  // Top priorities
  const critical = findings.filter((f) => f.severity === "critical");
  const high = findings.filter((f) => f.severity === "high");
  const priorities = [...critical, ...high].slice(0, 5);
  if (priorities.length > 0) {
    lines.push("### Top Remediation Priorities");
    lines.push("");
    for (const f of priorities) {
      const loc = findingLoc(f);
      lines.push(
        `1. **${f.title}** — ${cap(f.severity)}${loc ? ` at \`${loc}\`` : ""}`,
      );
    }
    lines.push("");
  }

  // Themes
  const themes = extractThemes(findings);
  if (themes.length > 0) {
    lines.push("### Major Exposure Themes");
    lines.push("");
    for (const theme of themes) {
      lines.push(`- ${theme}`);
    }
    lines.push("");
  }

  // Technical appendix
  lines.push("---");
  lines.push("");
  lines.push("## Technical Appendix — Full Findings");
  lines.push("");

  for (let i = 0; i < findings.length; i++) {
    const f = findings[i];
    lines.push(`### ${i + 1}. ${f.title}`);
    lines.push("");
    lines.push(`**Severity:** ${cap(f.severity)} · **Type:** ${f.finding_type.toUpperCase()}${f.rule_id ? ` · **Rule:** \`${f.rule_id}\`` : ""}`);
    lines.push("");

    const loc = findingLoc(f);
    if (loc) {
      lines.push(`**Location:** \`${loc}\``);
      lines.push("");
    }

    if (f.description) {
      lines.push(f.description);
      lines.push("");
    }

    // Trace
    if (f.taint_paths && f.taint_paths.length > 0) {
      lines.push("**Analysis Trace:**");
      for (const step of f.taint_paths) {
        lines.push(
          `- [${cap(step.step_kind)}] ${step.detail} — \`${step.file_path}:${step.line_start}\``,
        );
      }
      lines.push("");
    }

    // Remediation summary
    if (f.remediation) {
      lines.push("**How to fix:** " + extractFirstSentences(f.remediation.how_to_fix, 2));
      lines.push("");
      if (f.remediation.references.length > 0) {
        lines.push(
          "**References:** " +
            f.remediation.references
              .slice(0, 3)
              .map((r) => `[${r.title}](${r.url})`)
              .join(", "),
        );
        lines.push("");
      }
    }
  }

  // Footer
  lines.push("---");
  lines.push(
    `*Generated by SentinelCore on ${new Date().toISOString().split("T")[0]}*`,
  );

  return lines.join("\n");
}

function severityCounts(findings: Finding[]): Record<string, number> {
  const counts: Record<string, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0,
  };
  for (const f of findings) {
    counts[f.severity] = (counts[f.severity] || 0) + 1;
  }
  return counts;
}

function sevEmoji(sev: string): string {
  switch (sev) {
    case "critical": return "🔴";
    case "high": return "🟠";
    case "medium": return "🟡";
    case "low": return "🔵";
    default: return "⚪";
  }
}

function extractThemes(findings: Finding[]): string[] {
  const themes: string[] = [];
  const types = new Set(findings.map((f) => f.finding_type));
  if (types.has("sast") && types.has("dast")) {
    themes.push("Both static and dynamic analysis detected issues, indicating defense-in-depth gaps");
  }
  const hasCritical = findings.some((f) => f.severity === "critical");
  if (hasCritical) {
    themes.push("Critical-severity findings require immediate attention before production deployment");
  }
  const hasSecret = findings.some((f) => f.finding_type === "secret");
  if (hasSecret) {
    themes.push("Hardcoded credentials detected — rotate affected secrets and move to external configuration");
  }
  const hasInjection = findings.some((f) =>
    f.rule_id?.includes("SQL") || f.rule_id?.includes("CMD") || f.rule_id?.includes("XSS"),
  );
  if (hasInjection) {
    themes.push("Injection vulnerabilities present — prioritize input validation and parameterized queries");
  }
  return themes;
}

function findingLoc(f: Finding): string | null {
  if (f.file_path) {
    return f.line_number ? `${f.file_path}:${f.line_number}` : f.file_path;
  }
  if (f.url) {
    return [f.method, f.url].filter(Boolean).join(" ");
  }
  return null;
}

function extractFirstSentences(text: string, n: number): string {
  const sentences = text.match(/[^.!?\n]+[.!?]/g) || [text.slice(0, 120)];
  return sentences.slice(0, n).join(" ").trim();
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
