// Package export provides server-side report generation for SentinelCore
// findings and scans. These formatters are used by the API export endpoints
// so CI pipelines and automation clients can fetch reports without a browser.
//
// The output is identical in structure and safety to the frontend formatters.
package export

import (
	"fmt"
	"strings"
	"time"

	"github.com/sentinelcore/sentinelcore/internal/remediation"
)

// FindingData is the input for a single-finding export. It carries only the
// fields needed for rendering — the caller maps from DB rows.
type FindingData struct {
	ID          string
	Title       string
	Severity    string
	Status      string
	FindingType string
	RuleID      string
	Description string
	FilePath    string
	LineStart   int
	URL         string
	Method      string
	Parameter   string
	CreatedAt   time.Time
	TaintPaths  []TaintStep
	Remediation *remediation.Pack
}

// TaintStep is one evidence-chain step.
type TaintStep struct {
	StepIndex int
	FilePath  string
	LineStart int
	StepKind  string
	Detail    string
}

// ScanData is the input for a scan-level report.
type ScanData struct {
	ScanID       string
	ScanType     string
	ScanProfile  string
	Status       string
	ProjectName  string
	TargetLabel  string
	ArtifactName string
	CreatedAt    time.Time
	StartedAt    *time.Time
	FinishedAt   *time.Time
	Findings     []FindingData
}

// FindingMarkdown generates a complete Markdown export for one finding.
func FindingMarkdown(f FindingData) string {
	var b strings.Builder

	b.WriteString("# " + f.Title + "\n\n")
	b.WriteString("| Field | Value |\n|---|---|\n")
	b.WriteString(fmt.Sprintf("| **Severity** | %s |\n", cap(f.Severity)))
	b.WriteString(fmt.Sprintf("| **Status** | %s |\n", cap(f.Status)))
	b.WriteString(fmt.Sprintf("| **Type** | %s |\n", strings.ToUpper(f.FindingType)))
	if f.RuleID != "" {
		b.WriteString(fmt.Sprintf("| **Rule** | `%s` |\n", f.RuleID))
	}
	if loc := location(f); loc != "" {
		b.WriteString(fmt.Sprintf("| **Location** | `%s` |\n", loc))
	}
	b.WriteString("\n")

	if f.Description != "" {
		b.WriteString("## Description\n\n" + f.Description + "\n\n")
	}

	if len(f.TaintPaths) > 0 {
		b.WriteString("## Analysis Trace\n\n")
		for _, s := range f.TaintPaths {
			b.WriteString(fmt.Sprintf("%d. **[%s]** %s — `%s:%d`\n",
				s.StepIndex+1, cap(s.StepKind), s.Detail, s.FilePath, s.LineStart))
		}
		b.WriteString("\n")
	}

	if r := f.Remediation; r != nil {
		b.WriteString("## Why It Matters\n\n" + r.WhyItMatters + "\n\n")
		b.WriteString("## How to Fix\n\n" + r.HowToFix + "\n\n")
		b.WriteString("## Safe Example\n\n```java\n" + r.SafeExample + "\n```\n\n")
		if r.DeveloperNotes != "" {
			b.WriteString("## Developer Notes\n\n" + r.DeveloperNotes + "\n\n")
		}
		if len(r.VerificationChecklist) > 0 {
			b.WriteString("## Verification Checklist\n\n")
			for _, item := range r.VerificationChecklist {
				b.WriteString("- [ ] " + item + "\n")
			}
			b.WriteString("\n")
		}
		if len(r.References) > 0 {
			b.WriteString("## References\n\n")
			for _, ref := range r.References {
				b.WriteString(fmt.Sprintf("- [%s](%s)\n", ref.Title, ref.URL))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("*Generated by SentinelCore on %s*\n", time.Now().Format("2006-01-02")))
	return b.String()
}

// ScanReportMarkdown generates a full scan report with executive summary
// and technical appendix.
func ScanReportMarkdown(d ScanData) string {
	var b strings.Builder

	b.WriteString("# SentinelCore Scan Report\n\n")
	b.WriteString("## Scan Overview\n\n| Field | Value |\n|---|---|\n")
	b.WriteString(fmt.Sprintf("| **Scan ID** | `%s` |\n", d.ScanID[:min(8, len(d.ScanID))]))
	b.WriteString(fmt.Sprintf("| **Type** | %s |\n", strings.ToUpper(d.ScanType)))
	if d.ScanProfile != "" {
		b.WriteString(fmt.Sprintf("| **Profile** | %s |\n", cap(d.ScanProfile)))
	}
	b.WriteString(fmt.Sprintf("| **Status** | %s |\n", cap(d.Status)))
	if d.ProjectName != "" {
		b.WriteString(fmt.Sprintf("| **Project** | %s |\n", d.ProjectName))
	}
	if d.TargetLabel != "" {
		b.WriteString(fmt.Sprintf("| **Target** | %s |\n", d.TargetLabel))
	}
	if d.ArtifactName != "" {
		b.WriteString(fmt.Sprintf("| **Source Artifact** | %s |\n", d.ArtifactName))
	}
	b.WriteString(fmt.Sprintf("| **Created** | %s |\n", d.CreatedAt.Format("Jan 2, 2006 15:04")))
	if d.StartedAt != nil {
		b.WriteString(fmt.Sprintf("| **Started** | %s |\n", d.StartedAt.Format("Jan 2, 2006 15:04")))
	}
	if d.FinishedAt != nil {
		b.WriteString(fmt.Sprintf("| **Completed** | %s |\n", d.FinishedAt.Format("Jan 2, 2006 15:04")))
	}
	b.WriteString(fmt.Sprintf("| **Findings** | %d |\n\n", len(d.Findings)))

	// Executive summary
	counts := map[string]int{}
	for _, f := range d.Findings {
		counts[f.Severity]++
	}
	b.WriteString("## Executive Summary\n\n")
	b.WriteString(fmt.Sprintf("This %s scan identified **%d finding(s)** across the target.\n\n",
		strings.ToUpper(d.ScanType), len(d.Findings)))
	b.WriteString("### Severity Breakdown\n\n| Severity | Count |\n|---|---|\n")
	for _, sev := range []string{"critical", "high", "medium", "low", "info"} {
		if c := counts[sev]; c > 0 {
			b.WriteString(fmt.Sprintf("| %s **%s** | %d |\n", sevEmoji(sev), cap(sev), c))
		}
	}
	b.WriteString("\n")

	// Technical appendix
	b.WriteString("---\n\n## Technical Appendix — Full Findings\n\n")
	for i, f := range d.Findings {
		b.WriteString(fmt.Sprintf("### %d. %s\n\n", i+1, f.Title))
		b.WriteString(fmt.Sprintf("**Severity:** %s · **Type:** %s", cap(f.Severity), strings.ToUpper(f.FindingType)))
		if f.RuleID != "" {
			b.WriteString(fmt.Sprintf(" · **Rule:** `%s`", f.RuleID))
		}
		b.WriteString("\n\n")
		if loc := location(f); loc != "" {
			b.WriteString(fmt.Sprintf("**Location:** `%s`\n\n", loc))
		}
		if f.Description != "" {
			b.WriteString(f.Description + "\n\n")
		}
		if f.Remediation != nil {
			first := firstSentences(f.Remediation.HowToFix, 2)
			b.WriteString("**How to fix:** " + first + "\n\n")
		}
	}

	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("*Generated by SentinelCore on %s*\n", time.Now().Format("2006-01-02")))
	return b.String()
}

func location(f FindingData) string {
	if f.FilePath != "" {
		if f.LineStart > 0 {
			return fmt.Sprintf("%s:%d", f.FilePath, f.LineStart)
		}
		return f.FilePath
	}
	if f.URL != "" {
		parts := []string{}
		if f.Method != "" {
			parts = append(parts, f.Method)
		}
		parts = append(parts, f.URL)
		return strings.Join(parts, " ")
	}
	return ""
}

func cap(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func sevEmoji(s string) string {
	switch s {
	case "critical":
		return "🔴"
	case "high":
		return "🟠"
	case "medium":
		return "🟡"
	case "low":
		return "🔵"
	default:
		return "⚪"
	}
}

func firstSentences(text string, n int) string {
	var result []string
	for _, ch := range strings.SplitAfter(text, ".") {
		ch = strings.TrimSpace(ch)
		if ch == "" {
			continue
		}
		result = append(result, ch)
		if len(result) >= n {
			break
		}
	}
	return strings.Join(result, " ")
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
