package java

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/sentinelcore/sentinelcore/internal/sast/ir"
	"github.com/sentinelcore/sentinelcore/internal/sast/lang"
)

// ParseFile reads a .java file from disk and returns its SentinelIR module.
// absPath is the real filesystem location; relPath is the artifact-relative
// path that is stored in the module (and contributes to fingerprints). The
// separation lets the worker hand the engine stable, portable module paths
// even though the file itself lives under a scan-specific temp directory.
func ParseFile(absPath, relPath string) (*ir.Module, error) {
	src, err := os.ReadFile(absPath)
	if err != nil {
		return nil, fmt.Errorf("java frontend: read %s: %w", absPath, err)
	}
	return Parse(relPath, src), nil
}

// ParseSource parses a Java source byte slice that did not come from disk.
// Useful for tests and for the coming sidecar upgrade path, where the
// sidecar will stream bytes rather than paths.
func ParseSource(relPath string, src []byte) *ir.Module {
	return Parse(relPath, src)
}

// WalkJavaFiles walks the given directory tree and returns every path whose
// name ends in ".java". Used by the SAST worker (Chunk SAST-10) to enumerate
// files inside an extracted artifact bundle. The walker deliberately skips
// any directory named "target", "build", ".git", or ".idea" — these are
// the standard Java build and tooling directories and contain either
// generated bytecode or IDE state, not source we want to analyze.
func WalkJavaFiles(root string) ([]string, error) {
	var out []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			switch info.Name() {
			case "target", "build", ".git", ".idea", "node_modules":
				return filepath.SkipDir
			}
			return nil
		}
		// Delegate the extension→language map to internal/sast/lang so
		// adding a new language (Kotlin/Scala/Go/…) only edits one map
		// instead of every per-language walker.
		if lang.ForExtension(info.Name()) == "java" {
			out = append(out, path)
		}
		return nil
	})
	return out, err
}
